### ISSUE TITLE
fat-button not shown on some devices

### ISSUE THREAD

**Issue by ppachur** [rootzoll/konfetti-app#137]
During testing with holzoma there was _one_ device running Android 4.2.2 with touchwiz not showing the fat-button ui element to add a new task. The device also did not react on selecting a neighbourhood and always navigated to the Testnachbarschaft (on position0)

**Comment by ppachur** [comment]
This should probably not be addressed until it shows up on a second device.

**Comment by rootzoll** [comment]
I was able to simulate 4.2.2. - Material Design is broken on 4.2.2 
https://www.smartdroid.de/material-design-android-apps-stuerzen-auf-geraeten-mit-android-4-2-2-ab/

The app has a lot of UI flaws - we cannot fix a bug that big. But I was at least adding a normal button to the list on Android/4.2.2 devices, so that the app is at least funtioning, even if it will look broken a lot.

![bildschirmfoto 2017-02-28 um 11 59 41](https://cloud.githubusercontent.com/assets/2472225/23402793/741b6c52-fdad-11e6-853c-31f5b5fdddac.png)

**Comment by rootzoll** [comment]
the change of neighborhoods is working now (after finding the href bug)
