### ISSUE TITLE
move to production server with https

### ISSUE THREAD

**Issue by catarata02** [rootzoll/konfetti-app#33]

**Comment by rootzoll** [comment]
SSL is not easy possible with development server at Azure. We need to take care about this with the new production server that now will be rented with the money from the crowed funding.

**Comment by rootzoll** [comment]
When  moving to new production server the App needs to be adapted, too.

**Comment by rootzoll** [comment]
We have our new production server. Its a fresh Ubuntu 16.04 LTS. Would be great if someone will setup the server and document all steps so that if we need to move or change servers in the future.

Also we have a docker setup - there will we some steps to prepare the server to enable https with lets encrypt.

**Comment by ppachur** [comment]
implemented and deployed by 9178bb8be260fb2a8d16278570ccad1e99cd3bee
