### ISSUE TITLE
Password is sent in cleartext after account creation

### ISSUE THREAD

**Issue by ppachur** [rootzoll/konfetti-app#66]

**Comment by catarata02** [comment]
Is probably my mistake after the refactoring..  I will fix this.  Thx for finding out :)

**Comment by catarata02** [comment]
after account creation I cannot see the password at all..?? what did you mean with this issue.. ? if it is the clear text in the transfer, this will be solved when we have HTTPS enabled .. otherwise please be more specific.. If I register a user locally, I get this response: 
{
  "id": 54,
  "name": null,
  "imageMediaID": null,
  "spokenLangs": [
    "en"
  ],
  "activeOnParties": [],
  "adminOnParties": [],
  "reviewerOnParties": [],
  "lastActivityTS": 1482274713331,
  "pushActive": false,
  "pushSystem": null,
  "pushID": null,
  "clientId": 77,
  "clientSecret": "763570a0-26ed-492e-b3e1-9ed2c03179ab",
  "email": "test2@test.de"
}

**Comment by ppachur** [comment]
Ah sorry.. 

I meant the pw is sent in full and clear in the email. IMHO we shouldn't do this. We should at least replace all but 3 cahracters with stars or not show it at all.

**Comment by rootzoll** [comment]
"3 cahracters with stars" sounds like a good compromise for the beginning ... from there we can move in either direction.

**Comment by rootzoll** [comment]
not sending password in email anymore
